fisher_hub/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('logapp.urls')),
    path('library/', include('fish_info.urls')),
    path('maps/', include('maps.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maps/urls.py
from django.urls import path
from .views import AddressListView, AddressCreate, AddressView, save_mark

urlpatterns = [
    path('add_mark/', AddressCreate.as_view(), name='add_mark'),
    path('save_mark/', save_mark, name='save_mark'),
    path('show_marks/', AddressListView.as_view(), name='show_marks'),
    path('water_info/<int:pk>/', AddressView.as_view(), name='water_info'),

]

fish_info/models.py
from django.db import models


class FishClassification(models.Model):
    """Модель для класифікації риб"""
    classification = models.CharField(max_length=75)

    def __str__(self):
        return self.classification


class FishFamily(models.Model):
    """Модель для сімейства риб"""
    family = models.CharField(max_length=75)

    def __str__(self):
        return self.family


class FishDiet(models.Model):
    """Модель для опису харчування риб"""
    diet = models.CharField(max_length=55)

    def __str__(self):
        return self.diet


class Fish(models.Model):
    """Основна модель яка має інформацію з попередніх класів, а також свою унікальну"""
    img = models.ImageField()
    name = models.CharField(max_length=100)
    fish_classification = models.ForeignKey(FishClassification, on_delete=models.CASCADE)
    fish_family = models.ForeignKey(FishFamily, on_delete=models.CASCADE)
    fish_diet = models.ForeignKey(FishDiet, on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self):
        return self.name

templates/main/fish_library.html
{% extends "base.html" %}

{% block content %}
    <h2>Риботека</h2>
    <p>Тут ви знайдете інформацію про різні види риб та їх класифікацію.</p>
    <p>Для перегляду списку риб перейдіть за <a href="{% url 'fish_list' %}">посиланням</a>.</p>
    <p>Для перегляду риб за класифікацією перейдіть за <a href="{% url 'classification_list' %}">посиланням</a>.</p>
    <p>Для перегляду риб за сімейством перейдіть за <a href="{% url 'family_list' %}">посиланням</a>.</p>
    <p>Для перегляду риб за типом харчування перейдіть за <a href="{% url 'diet_list' %}">посиланням</a>.</p>
    <p>Повернутися на <a href="{% url 'home' %}">домашню сторінку</a>.</p>
{% endblock %}

templates/main/home.html
{% extends "base.html" %}

{% block content %}
    <h2>Ласкаво просимо!</h2>
    <p>Це домашня сторінка нашого сайту. Тут ви знайдете різноманітну інформацію яка може бути корисною для рибалок!</p>
    <p>Корисні посилання:</p>
    <ul>
        <li><a href="{% url 'fish_library' %}">Риботека</a></li>
        <li><a href="{% url 'add_mark' %}">Додати водойму</a></li>
        <li><a href="{% url 'show_marks' %}">Подивитись водойми</a></li>
        <li><a href="{% url 'profile' %}">Профіль</a></li>
    </ul>
{% endblock %}

templates/main/profile.html
{% extends "base.html" %}

{% block content %}
    <h2>Профіль користувача</h2>
    <div class="user-profile">
        <img src="{{ user.profile_picture.url }}" alt="Фото профілю">
        <div class="user-info">
            <p><h2>Користувач: <strong>{{ user.username }}</strong></h2></p>
            {% if user.bio %}
                <p><strong>Біографія:</strong></p>
                <p><h4>{{ user.bio }}</h4></p>
            {% else %}
                <p><strong>Біографія:</strong></p>
                <p><h4>Інформація відсутня</h4></p>
            {% endif %}
        </div>
    </div>
    <p><a href="{% url 'change_password' %}">Змінити пароль.</a></p>
    <p><a href="{% url 'edit_profile' %}">Редагувати профіль.</a></p>
    <p><strong><a href="{% url 'home' %}">Повернутися на домашню сторінку</a></strong></p>
{% endblock %}

templates/main/search_results.html
{% extends 'base.html' %}

{% block title %}Результати пошуку{% endblock %}

{% block content %}
    <h1>Результати за пошуком:</h1>
    {% if search_results %}
        {% if search_results.fish_results %}
            <h2>Знайдено за назвою риб:</h2>
            <ul>
                {% for fish in search_results.fish_results %}
                    <a href="{% url 'fish_detail' fish.id %}">{{ fish.name }}</a>
                {% endfor %}
            </ul>
        {% endif %}

        {% if search_results.diet_results %}
            <h2>Знайдено за типом харчування:</h2>
            <ul>
                {% for diet in search_results.diet_results %}
                    <a href="{% url 'diet_detail' diet.id %}">{{ diet.diet }}</a>
                {% endfor %}
            </ul>
        {% endif %}

        {% if search_results.family_results %}
            <h2>Знайдено за сімейством:</h2>
            <ul>
                {% for family in search_results.family_results %}
                    <a href="{% url 'family_detail' family.id %}">{{ family.family }}</a>
                {% endfor %}
            </ul>
        {% endif %}

        {% if search_results.classification_results %}
            <h2>Знайдено за класифікацією:</h2>
            <ul>
                {% for classification in search_results.classification_results %}
                    <a href="{% url 'classification_detail' classification.id %}">{{ classification.classification }}</a>
                {% endfor %}
            </ul>
        {% endif %}
    {% else %}
        <p>Результати пошуку відсутні.</p>
    {% endif %}
{% endblock %}