fisher_hub/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('logapp.urls')),
    path('library/', include('fish_info.urls')),
    path('maps/', include('maps.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maps/urls.py
from django.urls import path
from .views import AddressListView, AddressCreate, AddressView, save_mark

urlpatterns = [
    path('add_mark/', AddressCreate.as_view(), name='add_mark'),
    path('save_mark/', save_mark, name='save_mark'),
    path('show_marks/', AddressListView.as_view(), name='show_marks'),
    path('water_info/<int:pk>/', AddressView.as_view(), name='water_info'),

]

maps/models.py
from django.contrib.auth.models import User
from django.db import models
from fish_info.models import Fish


class WaterType(models.Model):
    """Модель типу водойми"""
    water_type = models.CharField(max_length=100)

    def __str__(self):
        return self.water_type


class Address(models.Model):
    """Модель адреси водойми"""
    water_name = models.TextField()
    water_type = models.ForeignKey(WaterType, on_delete=models.SET_NULL, null=True, blank=True)
    water_description = models.TextField(default='')
    price = models.CharField(max_length=20, blank=True, null=True)
    fish = models.ManyToManyField(Fish, blank=True)
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.water_name


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author.username} on {self.address.water_name}'

maps/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

maps/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, ListView, DetailView
from django.shortcuts import redirect
from .forms import CommentForm
from .models import Address, WaterType
from fish_info.models import Fish
from django.utils.translation import gettext as _

mapbox_api_key = "pk.eyJ1IjoiaWxsaWRhbjEyMyIsImEiOiJjbHVncWhvNm0yYXRoMmhxdTJyeGtvMnBuIn0.tn9RZUkv1QpKb3YehpYH8Q"


@require_POST
@login_required
def save_mark(request):
    """Збереження доданої водойми"""
    if request.method == 'POST':
        water_name = request.POST.get('water_name')
        water_type_name = request.POST.get('water_type')
        water_description = request.POST.get('water_description')
        longitude_str = request.POST.get('longitude')
        latitude_str = request.POST.get('latitude')
        fish_names = request.POST.getlist('fish')
        price_str = request.POST.get('price')

        # Функція для конвертації коми в крапку
        def convert_decimal_str(decimal_str):
            return decimal_str.replace(',', '.') if decimal_str else None

        # Конвертація координат і ціни з коми в крапку
        longitude = convert_decimal_str(longitude_str)
        latitude = convert_decimal_str(latitude_str)
        price = convert_decimal_str(price_str)

        if all([water_name, water_type_name, water_description, longitude, latitude, fish_names, price]):
            try:
                water_type, created = WaterType.objects.get_or_create(water_type=water_type_name)
                address = Address.objects.create(
                    water_name=water_name,
                    water_type=water_type,
                    water_description=water_description,
                    lat=latitude,
                    long=longitude,
                    price=price
                )
                # Відображення всіх існуючих об'єктів риб
                fish_objects = Fish.objects.filter(name__in=fish_names)
                address.fish.set(fish_objects)
                return JsonResponse({'success': True})
            except Exception as e:
                return JsonResponse({'success': False, 'error': str(e)})
        else:
            return JsonResponse({'success': False, 'error': _('Потрібно надати всі дані')})
    else:
        return JsonResponse({'success': False, 'error': _('Метод запиту має бути POST')})


class AddressCreate(CreateView):
    """Відображення карти на якій можна додавати адресу"""
    model = Address
    fields = ['water_name', 'water_type', 'water_description']
    template_name = 'maps/add_water.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['access_token'] = mapbox_api_key

        context['fish_names'] = Fish.objects.values_list('name', flat=True)
        return context


class AddressListView(ListView):
    """Відображення доданих адрес на карті"""
    model = Address
    template_name = 'maps/show_marks.html'
    context_object_name = 'addresses'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['access_token'] = mapbox_api_key
        context['fish_names'] = Fish.objects.values_list('name', flat=True)
        return context

    def get_queryset(self):
        return Address.objects.all()


class AddressView(DetailView):
    model = Address
    template_name = 'maps/address_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context

    def post(self, request, pk):
        address = Address.objects.get(pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.address = address
            comment.save()
            return redirect('water_info', pk=pk)
        else:
            return self.get(request, pk)

templates/maps/add_water.html
{% extends "base.html" %}

{% block content %}
<div id='map' style='width: 100%; height: 700px;'></div>
<script src='https://api.mapbox.com/mapbox-gl-js/v3.2.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v3.2.0/mapbox-gl.css' rel='stylesheet' />

{% if user.is_authenticated %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        mapboxgl.accessToken = '{{ access_token }}';
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11',
            center: [30.5234, 50.4501],
            zoom: 12,
            locale: 'uk'
        });

        map.on('click', function(e) {
            var lng = e.lngLat.lng;
            var lat = e.lngLat.lat;

            // Відображення форми для збереження водойми
            var popup = new mapboxgl.Popup({ offset: 25 })
                .setLngLat([lng, lat])
                .setHTML(
                    '<form id="waterForm">' +
                        '<label for="water_name">Назва:</label>' +
                        '<input type="text" id="water_name" name="water_name"><br>' +
                        '<label for="water_type">Тип:</label>' +
                        '<input type="text" id="water_type" name="water_type"><br>' +
                        '<label for="fish">Обрати рибу:</label>' +
                        '<div class="checkboxes">' +
                            '{% for fish_name in fish_names %}' +
                                '<label><input type="checkbox" name="fish" value="{{ fish_name }}">{{ fish_name }}</label>' +
                            '{% endfor %}' +
                        '</div>' +
                        '<label for="water_description">Опис:</label>' +
                        '<textarea id="water_description" name="water_description"></textarea><br>' +
                        '<label for="price">Ціна:</label>' +
                        '<input type="text" id="price" name="price"><br>' +
                        '<input type="hidden" id="longitude" name="longitude" value="' + lng + '">' +
                        '<input type="hidden" id="latitude" name="latitude" value="' + lat + '">' +
                        '<button type="submit">Зберегти</button>' +
                    '</form>'
                )
                .addTo(map);

            // Відправка даних форми при події submit
            document.getElementById('waterForm').addEventListener('submit', function(event) {
                event.preventDefault();
                var formData = new FormData(this);

                fetch('{% url "save_mark" %}', {
                    method: 'POST',
                    body: formData,
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}'
                    }
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        alert('Водойму успішно збережено!');
                        popup.remove();
                        window.location.reload(); // Оновлення сторінки
                    } else {
                        alert('Помилка при збереженні водойми: ' + data.error);
                    }
                })
                .catch(error => {
                    alert('Помилка при відправленні запиту: ' + error.message);
                });
            });
        });
    });
</script>

{% endif %}
{% endblock %}

templates/maps/address_detail.html
<!-- maps/address_detail.html -->

{% extends "base.html" %}

{% block content %}
    <h2>{{ object.water_name }}</h2>
    <p><strong>Тип водойми:</strong> {{ object.water_type }}</p>
    <p><strong>Опис:</strong> {{ object.water_description }}</p>
    <p><strong>Ціна:</strong> {% if object.price %}{{ object.price }}{% else %}Безкоштовно{% endif %}</p>
    <h3>Риби на водоймі:</h3>
    <ul>
        {% for fish in object.fish.all %}
            <img src="{{ fish.img.url }}" alt="{{ fish.name }}" width="100" height="100">
            <li>{{ fish.name }}</li>

        {% endfor %}
    </ul>
    <hr>
    <h3>Коментарі:</h3>
    {% if user.is_authenticated %}
        <form method="post" action="{% url 'water_info' pk=object.pk %}">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit">Додати коментар</button>
        </form>
    {% else %}
        <p>Увійдіть, щоб залишити коментар.</p>
    {% endif %}
    {% for comment in object.comment_set.all %}
        <p>{{ comment.author }} написав(ла) {{ comment.created_at|date:"F d, Y" }}</p>
        <p>{{ comment.text }}</p>
    {% empty %}
        <p>Поки немає коментарів.</p>
    {% endfor %}
{% endblock %}

templates/maps/show_marks.html
{% extends "base.html" %}

{% block content %}
<div id='map' style='width: 100%; height: 700px;'></div>
<script src='https://api.mapbox.com/mapbox-gl-js/v3.2.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v3.2.0/mapbox-gl.css' rel='stylesheet' />

<script>
    document.addEventListener('DOMContentLoaded', function() {
    mapboxgl.accessToken = '{{ access_token }}';
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [30.5234, 50.4501],
        zoom: 12,
        locale: 'uk'
    });

    {% for address in addresses %}
    var popupContent = '<h3>{{ address.water_name }}</h3><p>';
    {% if address.fish.all %}
    popupContent += '<strong>Риби на водоймі:</strong><br>';
    {% for fish in address.fish.all %}
    popupContent += '<img src="{{ fish.img.url }}" alt="{{ fish.name }}" width="50" height="50">';
    {% endfor %}
    {% endif %}
    popupContent += '</p>';
    popupContent += '<p><a href="{% url 'water_info' address.pk %}">{{ address.water_name }}</a></p>';

    // Перетворення координат у потрібний формат
    var lng = parseFloat('{{ address.long }}'.replace(',', '.'));
    var lat = parseFloat('{{ address.lat }}'.replace(',', '.'));

    // Встановлення маркера на карті
    new mapboxgl.Marker()
        .setLngLat([lng, lat])
        .setPopup(new mapboxgl.Popup().setHTML(popupContent))
        .addTo(map);
    {% endfor %}

    map.on('click', function(e) {
        var lng = e.lngLat.lng;
        var lat = e.lngLat.lat;

        // Відображення маркера на карті
        var markerElement = document.createElement('div');
        markerElement.className = 'marker';
        new mapboxgl.Marker(markerElement)
            .setLngLat([lng, lat])
            .addTo(map);
    });
});

</script>
{% endblock %}